import {NgModule} from '@angular/core';

// Module
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
import { RouterModule } from '@angular/router';

// Components
import {AppComponent} from './app.component';
import { OrderComponent } from './orders/orders.component';
import { HomeComponent } from './home/home.component';
import { NotFoundComponent } from './shared/notFound.component';
import { ProductModule } from './products/products.module';

// decorator
@NgModule({
    // all your module & routing
    imports: [
        BrowserModule,
        FormsModule,
        HttpClientModule,
        RouterModule.forRoot([
            {path: 'orders', component: OrderComponent},
            {path: 'home', component: HomeComponent},
            {path: '', redirectTo: 'home', pathMatch: 'full'},
            {path: '**', component: NotFoundComponent}
        ]),
        ProductModule
    ],
    // all your component & pipes
    declarations: [
        AppComponent,
        OrderComponent,
        HomeComponent,
        NotFoundComponent,
    ],
    // only and only first component
    bootstrap: [
        AppComponent
    ],
    // all the services
    providers: []
})

export class AppModule {

}

